language: python
python:
  - "3.6"
install:
  - python -m pip install --upgrade pip
  - python setup.py install
  - python -m pip install -r test_requirements.txt
before_script:
  - export FLASK_APP=unittests/server.py
  - flask run &
script:
  - pytest --cov=compliance_suite/ --cov-report=term-missing unittests/
after_success:
  - coveralls
  - bash ./scripts/deploy-gh-pages.sh
after_script:
  - kill %1
env:
  global:
  - GH_USER: ga4gh-rnaseq
  - GH_REPO: rnaget-compliance-suite
