servers:
  - server_name: Caltech
    base_url: https://felcat.caltech.edu/rnaget/
    implemented:
      projects: true
      studies: true
      expressions: true
      continuous: true
    
  - server_name: Centre for Genomic Regulation
    base_url: https://genome.crg.cat/rnaget/
    token: SERVER_API_KEY_CRG
    implemented:
        projects: true
        studies: true
        expressions: true
        continuous: true
    
  - server_name: CanDIG
    base_url: https://candig.bcgsc.ca/rnaget/
    token: SERVER_API_KEY_CANDIG
    implemented:
        projects: true
        studies: true
        expressions: true
        continuous: false
