servers:
  - server_name: Caltech
    base_url: https://felcat.caltech.edu/rnaget/
    implemented:
      projects: true
      studies: true
      expressions: true
      continuous: true

  - server_name: Centre for Genomic Regulation
    base_url: https://genome.crg.cat/rnaget/
    token: abcdefuvwxyz
    implemented:
        projects: true
        studies: true
        expressions: true
        continuous: true