servers:
  - serverA:
    base_url: https://felcat.caltech.edu/rnaget/
    
    projects:
      - projectA:
        id: 43378a5d48364f9d8cf3c3d5104df560
        filters:
          - version: 1.0
          - name: PCAWG
    
    studies:
      - studyA:
        id: 6cccbbd76b9c4837bd7342dd616d0fec
        filters:
          - version: 1.0
          - name: PCAWG
    
    expressions:
      - expressionA:
        id: 2a7ab5533ef941eaa59edbfe887b58c4
        filters:
          - studyID: 6cccbbd76b9c4837bd7342dd616d0fec
  
  

